extends:
  - airbnb-base
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:cypress/recommended
  - plugin:react/recommended

plugins:
  - jest
  - cypress

env:
  node: true

parserOptions:
  ecmaVersion: 2020
  sourceType: module

rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - always
  no-console: 0
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-use-before-define:
    - error
    - functions: false
  object-curly-newline:
    - error
    - consistent: true
  object-curly-spacing:
    - error
    - always
  comma-dangle:
    - error
    - always-multiline
  require-await:
    - error
  no-unused-vars:
    - error
    - argsIgnorePattern: next
  prefer-arrow-callback:
    - error
  func-names:
    - error
